### ISSUE TITLE
YAML formatting broken

### ISSUE THREAD

**Issue by disrupted** [mikew/prettier_d_slim#8]
Thanks for this cool little helper, it has made prettier much more usable/enjoyable for me.

Unfortunately YAML formatting doesn't seem to work.

file contents:

```yaml
version: 2
updates:
  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directory:  "/"
    schedule:
          interval: "daily"

```

---
Using `prettier`:

```sh
❯ cat .github/dependabot.yml | prettier --stdin-filepath .github/dependabot.yml
version: 2
```
```yaml
updates:
  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
```

→ formatting applied correctly

---
Using `prettier_d_slim`:

```sh
❯ cat .github/dependabot.yml | prettier_d_slim --stdin --stdin-filepath .github/dependabot.yml
```
```yaml
version: 2
updates:
  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directory:  "/"
    schedule:
          interval: "daily"
```

→ no formatting applied
